### ISSUE TITLE
Cold Guide Errors

### ISSUE THREAD

**Issue by Rspigler** [JWWeatherman/yetihosted#18]
guide3.yeticold.com Still has the 'delete USB drive' errors.

The USB should be cleared when plugged in, before the PSBT is placed on the device. That way, there is only a single file on the USB.  When transferring to the other computer, it doesn't make sense to wipe the USB, because then there is no file/PSBT to transfer.

Send: Step 7 should delete the USB before copying the File.
Send: Step 8 is good as is
Send: Step 14 is good as is
Send: Step 15 should not delete the file

**Comment by JWWeatherman** [comment]
Will went through and changed a bunch of things including this issue, Thanks.
