### ISSUE TITLE
Yeti Hosted appears to have another color and bold in the header

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/yetihosted#19]
Color might be due to VM, but bold is not.

<img width="815" alt="Screen Shot 2021-01-28 at 6 50 11 PM" src="https://user-images.githubusercontent.com/32912678/106212993-c6e94900-6199-11eb-8f01-79f3871fdce7.png">

**Comment by willweatherman** [comment]
Different browsers different boldness/colors.
