### ISSUE TITLE
Step 10/11 Issues Level 3

### ISSUE THREAD

**Issue by Rspigler** [JWWeatherman/yetihosted#21]
Issue with Step 10/11:

The CD's have all already been labelled in Step 1 (which is good).  Clarify for user.  These are the substeps that need changing:  (Because there are no blank CD's, and no CD's to label).

Step 10:

1.  Insert your CD labelled 'Seed 1'
4.  When you see "Data CD successfully burnt" click Close and then remove.
5.  Repeat steps 1 through 4 above with your other six Seed CD's.

Step 11:

1.  Insert one of your Descriptor CD's.
4.  When you see 'Data CD successfully burnt' click Close and then remove.
5.  Repeat steps 1 through 4 above with your other six Descriptor CDs then click Next to continue.

These changes need to also take place for Level 1 and 2 appropriately.
These changes need to take place for video edits that are waiting.  @willweatherman @JWWeatherman 

Please ping when done, thanks!

**Comment by JWWeatherman** [comment]
@Rspigler include the url next time if you think of it. Makes finding the correct files easier. Working on this now.

**Comment by Rspigler** [comment]
@diggitydman told me this was fixed
